### ISSUE TITLE
Support more models

### ISSUE THREAD

**Issue by jackwish** [jackwish/tflite2onnx#11]
* [Models in TFLite guide](https://www.tensorflow.org/lite/guide/hosted_models)
* [TensorFlow Hub TFLite models](https://tfhub.dev/s?deployment-format=lite)
* [Slim pretrained models](https://github.com/tensorflow/models/tree/master/research/slim#pre-trained-models)

**Comment by y-fujii** [comment]
[Google MediaPipe](https://google.github.io/mediapipe/) has some useful TFLite files, whose original TensorFlow models are not released.  Currently there is no way to get ONNX.

<https://google.github.io/mediapipe/solutions/models>

It would be great if tflite2onnx could work on these files.

**Comment by jackwish** [comment]
@y-fujii Thanks for reporting this, I didn't even know that there are so many models are release in TFLite format only. Yes, it would be great if we can enable these models. It does take time to achieve that, hoping that we may have a joint force :)

**Comment by IkbeomJeon** [comment]
You can convert objectron examples in my fork. (I requested pull.)

objectron : https://google.github.io/mediapipe/solutions/objectron.html

See my pull request : https://github.com/jackwish/tflite2onnx/pull/21

**Comment by jackwish** [comment]
Going to drop the model level CI test now. There are potential license issues and it requires effort to maintain.
