### ISSUE TITLE
Rank of shape of Reshape operator

### ISSUE THREAD

**Issue by zhenhuaw-me** [jackwish/tflite2onnx#16]
<img width="751" alt="2rank-reshape" src="https://user-images.githubusercontent.com/4936589/91784379-5c0d0380-ec35-11ea-9d9b-07ba9e349cd9.png">

In the _Squeezenet_ [hosted by TensorFlow](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/lite/g3doc/guide/hosted_models.md#floating-point-models), we found that the `Reshape` of the model has a 2 rank `shape` input, which is not supported by ONNXRuntime (as of `1.4.0`).

```
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/tensor/reshape.h:24 virtual onnxruntime::common::Status onnxruntime::Reshape::Compute(onnxruntime::OpKernelContext *) const shapeTensor->Shape().NumDimensions() == 1 was false. A shape tensor must be a vector tensor.
```

This `shape` of `Reshape` is pre-computed by TensorFlow Lite converter from the pattern below. Where `AvgPool - Shape` should outputs `[1, 1, 1, 1001]`, then `StridedSlice` to `[1]`, and `Pack` (now `Stack`) with `[-1,]` to be `[[1,], [-1]]` which is 2 rank.
<img width="693" alt="shape-tf" src="https://user-images.githubusercontent.com/4936589/91784473-9a0a2780-ec35-11ea-9bbd-5f5e140b125d.png">

Everything looks good in the path of TensorFlow -> TensorFlow Lite -> TFLITE2ONNX -> ONNX, but ONNXRuntime doesn't support all scenarios. Maybe we need to find a workaround for it, for example, always flatten the `shape` for `Reshape`.

**Comment by erizmr** [comment]
Hi Jackwish,
It seems there is another format `reshape` operator shown below, one input and one attribute, violating `assert(op.InputsLength() == 2)` in the `reshape.py`. 
![image](https://user-images.githubusercontent.com/33411325/98453515-e1d78e80-2151-11eb-9b46-76ab93e9d8ed.png)

I did a quick try (shown below, using the attribute `new_shape` as the second input) but seems not working. Would you mind sharing some ideas about it? Thanks!
```
        # options
        op_opt = op.BuiltinOptions()
        option = tflite.ReshapeOptions()
        option.Init(op_opt.Bytes, op_opt.Pos)
        sp = option.NewShapeAsNumpy()
        sp = self.TFactory.createVector(data, sp)
        sp.dtype = mapping.DTYPE_NAME2ONNX['int64']
        sp.addConsumer(self)
        self.inputs.append(sp)
```

**Comment by jackwish** [comment]
@erizmr Thank you for reporting this issue, would you mind to raise this issue as a `bug` and attach the TFLite model you are trying with? We may need to deep dive to find out what's wrong.

**Comment by erizmr** [comment]
Sure. I will do that. Thanks!
