### ISSUE TITLE
Operator request: quantized SSD MobileNet

### ISSUE THREAD

**Issue by Roberto7766** [jackwish/tflite2onnx#20]
**Note**: Currently, we only accept [TensorFlow Lite builtin operators](https://jackwish.net/tflite/docs/BuiltinOperator.m.html) request.

**What is the TensorFlow Lite operator you need**
During the conversion I obtain :"NotImplementedError: Unsupported TFLite OP: 14"
The .tflite file is available here:
http://storage.googleapis.com/download.tensorflow.org/models/tflite/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.zip

**What kind of service you are trying to deploy your model?**
Object detection

**Would you like to contribute the operator?**
Yes

**Additional context**

**Comment by jackwish** [comment]
Hi @Roberto7766, thanks for reporting this! Do you have time to enable the operator, we have a guide of _[how to enable new operator](https://github.com/jackwish/tflite2onnx/blob/master/docs/how-to-enable-new-operator.md)_ (not updated in `v0.3`, I can update it soon).

**Comment by Guriido** [comment]
@Roberto7766 
OP 14 is the Logistic operator, which is already supported in the master branch but not yet in the latest PyPI release.
I suggest installing from source, as described here: https://github.com/jackwish/tflite2onnx#installation

**Comment by jackwish** [comment]
Planning `v0.3.1` release by the end of this year, which should include Logistic

**Comment by jackwish** [comment]
@Roberto7766 I am going to close this issue as Logistic has been enabled. Please reopen if the model fails still. Thanks for reporting this issue.
