### ISSUE TITLE
Enquiry about parsing optional input 

### ISSUE THREAD

**Issue by erizmr** [jackwish/tflite2onnx#22]
Hi jackwish,

Thanks for sharing your awesome frame!
I am trying to enable a new operator `Resize` from `resize_bilinear`, the ONNX description of `Resize` is shown below:
![image](https://user-images.githubusercontent.com/33411325/98451518-38d36880-213e-11eb-87ff-c401ffe09c38.png)
Only one of 'scales' and 'size' should be specified in this case, I am not sure how to 'skip' one of the arguments (also the `roi`) when implementing the parse part, because it seems the inputs are store in a list without a key.
I am wondering if you could share any suggestions about it?

Thanks,
Mingrui

**Comment by jackwish** [comment]
Hi @erizmr thank you for reporting this issue. This is really a good example of the operator semantic divergence between TFLite and ONNX.

I checked the `Resize` example ([`resize_upsample_sizes_nearest_round_prefer_ceil_asymmetric` example of `Resize`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#resize)) of ONNX, it seems we can simply leave the tensor field as empty when creating the operator.
```
node = onnx.helper.make_node(
    'Resize',
    inputs=['X', '', '', 'sizes'],
    outputs=['Y'],
    mode='nearest',
    coordinate_transformation_mode='asymmetric',
    nearest_mode='round_prefer_ceil'
)
```

In tflite2onnx, we may have a helper to create _empty tensor_ and make it as inputs of an operator. The challenge here is, graph level handling (e.g. data layout handling) may be impacted as we seem to assume tensors are not empty.

Do you have a simplified TFLite model that contains the `resize_bilinear` operator at hand? We may start with that to check what may happen.

**Comment by erizmr** [comment]
Thansk for your reply. @jackwish 
Here is a simple TFLITE model for `resize_bilinear` generated by `tf.compat.v1.image.resize_bilinear`:
[model_resize_bilinear.tflite](https://drive.google.com/file/d/16pp9gjkxzavG38gDClzGVmjFaDUSJ6R5/view?usp=sharing)
```
import tensorflow as tf
# operator inputs
img = tf.keras.Input(dtype='float32', name='input', shape=([4, 4, 3]), batch_size=1)
scale = (8, 8)
# operator
resize = tf.compat.v1.image.resize_bilinear(img, scale, half_pixel_centers=True)
# build Keras model
model = tf.keras.Model(inputs=[img], outputs=[resize])
# convert to TFLite model
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
# save it
with open('model_resize_bilinear.tflite', 'wb') as f:
  f.write(tflite_model)
```

<img src="https://user-images.githubusercontent.com/33411325/98595413-ddd07b80-22cd-11eb-9ea2-b5ab1b0762a1.png" width="350"/>

There are two inputs: `input`(called `images` in docs TensorFlow, NHWC format) and `size` (a tuple of new_height and new_width after resizing, int32 only)

Maybe we can start with this simple model.

**Comment by jackwish** [comment]
@erizmr thank you for the update. May I know which version of the TensorFlow you are using to generate this TFLite model? It's interesting that the `new_height` and `new_width` attributes are not listed in [the TFLite model API doc](https://jackwish.net/tflite/docs/ResizeBilinearOptions.m.html) which is automatically generated from TensorFlow 2.3.0.

Background: any attributes in TFLite model shall have a reader method in its parser, e.g. [`NewShape` of `Reshape`](https://jackwish.net/tflite/docs/ReshapeOptions.m.html).

**Comment by erizmr** [comment]
The model is generated from TensorFlow 2.3.1. The doc for the method `tf.compat.v1.image.resize_bilinear` used is shown in the [link](https://www.tensorflow.org/api_docs/python/tf/compat/v1/image/resize_bilinear).

I also checked the definition for this operator [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/image_ops.cc):
<img src='https://user-images.githubusercontent.com/33411325/98649704-caee9300-232f-11eb-8e34-37d696b7f2f7.png' width=600>

It seems there is indeed no attrs named `new_height` and `new_width`, which is quite interesting.

**Comment by jackwish** [comment]
That's the definition of TensorFlow operator which is not always same as its TFLite peer.

**Comment by erizmr** [comment]
Hi @jackwish, I tried the empty tensors(from `np.array([])` ) idea you have mentioned before. It actually works. Here is an example:

<img src ='https://user-images.githubusercontent.com/33411325/98753207-b7890980-23bb-11eb-991e-eec0740b60c6.png' width=500>

Maybe I can send a pull request to share the code if you wish.

**Comment by jackwish** [comment]
Cool! A PR would be great! Thanks for the update @erizmr
