### ISSUE TITLE
Reshape - spatial semantic removed but post operators need it still

### ISSUE THREAD

**Issue by erizmr** [jackwish/tflite2onnx#28]
**Describe the bug**
 `Reshape` is executed in C-like by default, i.e. with the last axis index changing fastest, back to the first axis index changing slowest. Therefore, in a condition that **there are implicit layout operators (such as `Conv`) before the `Reshape`**, different input layout will affect the reshaped result e.g. (1,4,4,8) -> (1, 128) is different to (1,8,4,4) -> (1, 128). Although the output shape is the same, the entries in the tensor will be in a different order. 
(onnx `Reshape` is similiar to `numpy.reshape`. A simple numpy example shown in the image below describes this condition, the output of `a.reshape((1, 12))` and `b.reshape((1, 12))` is different)

<img src = https://user-images.githubusercontent.com/33411325/99135121-af79d580-2618-11eb-8a0e-4f9bbbb77431.png width=500>

**Possible solution**
A possible solution is to add an additional `Transpose` before the `Reshape` in this certain condition.
I have developed a naive `fakeTranspose` (mimicking the `fakeBroadingcast`) method to add a `Transpose` before all the `Reshape` currently (shown in the image below). But it indeed needs a further judgment for whether there are implicit layout operators before this 'Reshape'.

<img src = https://user-images.githubusercontent.com/33411325/99135008-2c587f80-2618-11eb-94ea-14645ba670b7.png width=350>
How do you think about this solution? @jackwish  And it will be great if you can share some suggestions about how to judge for this specific case (actually quite common)?  Thanks!

**Additional context**
The bug seems "escaped" from the current graph level tests. I didn't' notice this problem until feeding the same input into the `.tflite` model and its corresponding`.onnx`, comparing the exact output values between them. Maybe it will be great if we can add some tests comparing the exact output values before and after in addition to the computation graph.

**Comment by jackwish** [comment]
@erizmr This is same as https://github.com/jackwish/tflite2onnx/issues/23 right? That issue was closed automatically by your PR.

**Comment by erizmr** [comment]
Hi @jackwish , sorry for didn't clarify this issue well, I think it is different from #23.
Here is a simple test case.
### Current case

Original TFlite Model           |  Converted ONNX Model
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/33411325/99144163-7747b680-265b-11eb-9d45-027415e22adf.png )  |  ![](https://user-images.githubusercontent.com/33411325/99144167-83cc0f00-265b-11eb-923e-978c2f2aa74b.png )

It looks right until we try to put them in runtime, and feed some actual values.
#### Test result
![image](https://user-images.githubusercontent.com/33411325/99144472-1a013480-265e-11eb-87c7-c318284a16d1.png)
 
The values in the output tensor are placed in a different order, resulting a large RMSE error for each entry.
And the reason I suspect is that`Reshape` is executed in C-like by default, i.e. with the last axis index changing fastest, back to the first axis index changing slowest.
 
### Add an addition `Transpose` before `Reshape`
Original TFlite Model           |  Converted ONNX Model \(with an additional `Transpose`)
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/33411325/99144163-7747b680-265b-11eb-9d45-027415e22adf.png )  |  ![](https://user-images.githubusercontent.com/33411325/99144562-c80cde80-265e-11eb-9fd9-b6292192d9db.png )

#### Test result
![image](https://user-images.githubusercontent.com/33411325/99144572-d9ee8180-265e-11eb-99e8-ec4e2ff259c7.png)

Now the RMSE is 0 and the values in the tensor are placed in the same order.

**Comment by jackwish** [comment]
Hmmm, interesting... `Reshape` should just touch the shape but not the data.

For the first comment https://github.com/jackwish/tflite2onnx/issues/28#issue-742889412, `a.reshape((1, 12))` and `b.reshape((1, 12))` are different because `a` and `b` are different - `b` is transposed from `a`. So the different reshaped result is expected.

For your model test in the second comment https://github.com/jackwish/tflite2onnx/issues/28#issuecomment-727177554, did you test it with `tflite2onnx` test infrastructure or another tool? To verify that, you can try the TFLite model with the test infrastructure (check [`test_networks.py`](https://github.com/jackwish/tflite2onnx/blob/master/tests/test_networks.py)) which runs and compares with TFLite and ONNXRuntime with data layout aware.

**Comment by erizmr** [comment]
I double-checked the test by using the `test_networks.py`(put the model name inside the `NETWORK_LIST` of function `test_networks`),  and got the log below:
```
2020-11-14 21:24:05,588 I [tflite2onnx][convert.py:46] Converted ONNX model: reshape_with_implicit_layout_input.onnx
2020-11-14 21:24:05,589 D [shrub][onnx.py:55] running reshape_with_implicit_layout_input.onnx
2020-11-14 21:24:05,589 D [shrub][onnx.py:22]  parsing reshape_with_implicit_layout_input.onnx
2020-11-14 21:24:05,590 D [shrub][tflite.py:98] running /Users/zmr/work_environment/tflite2onnx/assets/tests/reshape_with_implicit_layout_input.tflite
2020-11-14 21:24:05,591 D [shrub][tflite.py:104] Inputs: [{'name': 'input', 'index': 0, 'shape': array([1, 2, 2, 3], dtype=int32), 'shape_signature': array([1, 2, 2, 3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
2020-11-14 21:24:05,591 D [shrub][tflite.py:105] Outputs: [{'name': 'Identity', 'index': 5, 'shape': array([ 1,  1, 12], dtype=int32), 'shape_signature': array([ 1,  1, 12], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
2020-11-14 21:24:05,592 E [shrub][network.py:117] Tensor 0 mismatch!
Traceback (most recent call last):
  File "/Users/zmr/work_environment/tflite2onnx/tests/test_networks.py", line 37, in <module>
    test_networks()
  File "/Users/zmr/work_environment/tflite2onnx/tests/test_networks.py", line 33, in test_networks
    end2end_test(net, 'NCHW')
  File "/Users/zmr/work_environment/tflite2onnx/tests/test_networks.py", line 23, in end2end_test
    assert(shrub.network.cmpTensors(onnx_ret, tflite_ret, useLayout=use_layout))
AssertionError
```
From my side, there is a tensor mismatch as the case we discussed above in the second comment #28 ([comment](https://github.com/jackwish/tflite2onnx/issues/28#issuecomment-727177554)).
It will be great if you can try to reproduce it using the model below. Thanks!

The model I used is [reshape_with_implicit_layout_input.tflite.zip](https://github.com/jackwish/tflite2onnx/files/5541490/reshape_with_implicit_layout_input.tflite.zip):
<img src=https://user-images.githubusercontent.com/33411325/99157418-8dd42900-26c0-11eb-98c5-bd6f77c888ff.png width=500>

**Comment by jackwish** [comment]
I know what’s going on here. Conceptually, the Conv output in your example
holds spatial information which is described by data layout implicitly.
Reshape removes that information.

Did you get this in a valid model? For the image classification case,
Reshape is used when spatial information has been transformed into
classification information where we can just manipulate the shapes.

We need to understand the semantics of the particular model, and then to
figure out what we can do.

**Comment by erizmr** [comment]
Maybe we can start from a production model from google mediapipe: [hand_landmark.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark.tflite)
(I tested it and got same AssertionError shown below, we can observed that both `regressor` and `classificator` gave incompatible results between `onnx` and original `tflite`)

```
2020-11-15 09:19:50,941 D [shrub][tflite.py:98] running /Users/zmr/work_environment/tflite2onnx/assets/tests/hand_landmark.tflite
2020-11-15 09:19:50,942 D [shrub][tflite.py:104] Inputs: [{'name': 'input_1', 'index': 0, 'shape': array([  1, 224, 224,   3], dtype=int32), 'shape_signature': array([  1, 224, 224,   3], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
2020-11-15 09:19:50,942 D [shrub][tflite.py:105] Outputs: [{'name': 'Identity', 'index': 165, 'shape': array([ 1, 63], dtype=int32), 'shape_signature': array([ 1, 63], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'Identity_1', 'index': 167, 'shape': array([1, 1], dtype=int32), 'shape_signature': array([1, 1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'Identity_2', 'index': 169, 'shape': array([1, 1], dtype=int32), 'shape_signature': array([1, 1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
onnx output shape [(1, 63), (1, 1), (1, 1)]
tflite output shape [(1, 63), (1, 1), (1, 1)]
--------
onnx output regression [[ -7.6073546  -27.978569    -0.19374599 -16.036154   -24.49908
    0.310351    -7.7335978  -11.883962     6.2123504   -7.78824
  -13.430719    10.554062   -19.322495   -15.561377    21.562256
  -11.941065     8.27174      7.367118    -5.9465976    0.03702927
   -7.0028114   -1.9284966  -10.809402   -13.441153   -13.135593
  -11.517147    -9.35179     -9.261816     9.969861     7.0518885
  -11.612432     5.492342     2.10589    -10.226494    -1.4288185
    3.2325594  -10.720483    -0.66905916   8.064309    -2.8370264
    3.6340456    4.784828    -8.951375     3.2246165    0.86668086
   -4.871875    -6.3284388  -15.344627   -14.160993    -1.0720387
  -13.983957     3.0888221  -11.677685    10.193252   -16.333677
  -16.881477     5.201307   -15.730751   -12.716439    -4.168335
  -11.1376295    5.5690546   -1.4117393 ]]
tflite output regression [[ 1.35871979e+02  1.69058502e+02 -9.39190388e-04  1.01933876e+02
   1.40121124e+02  1.67699890e+01  8.46469879e+01  1.18316307e+02
   2.66238499e+01  7.63596115e+01  9.87020264e+01  3.33936539e+01
   7.19490585e+01  8.53927994e+01  3.92486877e+01  9.52651367e+01
   9.96494980e+01  3.14512634e+01  8.48083191e+01  8.61924133e+01
   4.24079437e+01  8.28852768e+01  8.39903641e+01  4.77232628e+01
   8.21106644e+01  8.12834930e+01  5.14650917e+01  1.15890472e+02
   9.93503189e+01  2.51773911e+01  1.08343842e+02  8.88825989e+01
   3.65208740e+01  1.05980423e+02  9.00624237e+01  3.75224228e+01
   1.04406754e+02  9.22210999e+01  3.86120453e+01  1.33215378e+02
   1.02880501e+02  2.01608276e+01  1.28175430e+02  9.18047180e+01
   2.98324928e+01  1.25691475e+02  9.36681290e+01  2.85918007e+01
   1.23241882e+02  9.54212189e+01  2.78829327e+01  1.47158340e+02
   1.08617302e+02  1.58605680e+01  1.46409393e+02  9.93111343e+01
   2.53306408e+01  1.43596191e+02  1.02880394e+02  2.87079163e+01
   1.40688202e+02  1.04027039e+02  3.20702934e+01]]
--------
onnx output classfication1 [[1.]]
tflite output classfication1 [[1.136177e-06]]
--------
onnx output classfication2 [[0.]]
tflite output classfication2 [[0.99942666]]
--------
2020-11-15 09:19:50,968 E [shrub][network.py:117] Tensor 0 mismatch!
Traceback (most recent call last):
  File "/Users/zmr/work_environment/tflite2onnx/tests/test_networks.py", line 50, in <module>
    test_networks()
  File "/Users/zmr/work_environment/tflite2onnx/tests/test_networks.py", line 46, in test_networks
    end2end_test(net, 'NCHW')
  File "/Users/zmr/work_environment/tflite2onnx/tests/test_networks.py", line 35, in end2end_test
    assert(shrub.network.cmpTensors(onnx_ret, tflite_ret, useLayout=use_layout))
AssertionError
```

The output part of this model is shown below. I think the reason might be that weights in `Gemm` are placed in original order as tflite while its input from `Reshape` has a "transposed" order propagated from the input at the very beginning of this network, which caused the incompatibility 

Original tflite            |  Converted onnx
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/33411325/99180836-9b6dcb00-2721-11eb-8e87-d4614412da96.png)  |  ![](https://user-images.githubusercontent.com/33411325/99181134-6c0c8d80-2724-11eb-999e-ba8d9a87510f.png)

For `mobilenet_v1_0.25_128` shown below ( the default test case in the `test_networks()` function, which is similar to the image classification case you have mentioned ), I think it is a case that will not be affected by the incompatible order.  There is no `Gemm` layer after `Reshape` and the 'Softmax' is just a weights free output layer. So if we just want to select the entry with the highest probability, the placing order of them is not important anymore. Also, the `Reshape` here mapping a tensor with shape 1x1000x1x1 to 1x1001, which degenerated to a `squeeze` losing its generality probably.

mobilenet_v1_0.25_128          
:-------------------------:
![](https://user-images.githubusercontent.com/33411325/99181479-d7eff580-2726-11eb-9439-8d2fb2f3c7e4.png)

**Comment by jackwish** [comment]
Hmmm, interesting, the _landmark_ model just removes the spatial semantic wildly which the post operators rely on implicitly still. Maybe we really need to insert a `Transpose` to handle it. Really good catch! @erizmr 

So, if the input (or output) tensor of `Reshape` holds a special data layout semantic, we need to insert `Transpose` before (or after) the `Reshape` operator. I am not sure how your `fakeTranspose` works but I have a concern here ->

Before, I took `Transpose` as an _Attribute_ operator (see in [this section](https://jackwish.net/2020/Convert-TensorFlow-Lite-models-to-ONNX.html#propagation-based-approach)) which needs a _post transformation_ to manipulate the attribute `perm` (similar to [attribute `axis` of `Concat`](https://github.com/jackwish/tflite2onnx/blob/master/tflite2onnx/op/concat.py)). If we insert a `Transpose` between `Conv` and `Reshape`, we need to be carefull about how to set the `perm`. In the end, we need the `perm` of `Transpose` to convert `NCHW` to `NHWC`, which should be `[0, 2, 3, 1]`. But if we set that during `Reshape` parsing, the `perm` will change into something unexpected in layout propagation, which results in failure still.

I have not seen `Transpose` needs to be an _Attribute_ operator in real model yet, so as a quick try, maybe we can make it a `Terminate` (just let `propatableTensors()` return an empty list) so we can safely get the _landmark_ model worked. If we are going to do this, I suggest to log a warning in `Transpose.transform()` that it's `perm` and data layout of output is not transformed currently. What do you say?

Thank you for this great finding! I think we are on the correct path :)

**Comment by erizmr** [comment]
Happy to discuss this with you! And sorry for the confusing name I gave for this issue and thanks for correcting it! It's much more readable now. @jackwish 

The `Transpose` operator in the code base now is already a `Terminate` and I didn't touch it during the development currently.

The naive `fakeTranspose` I developed now was called in the `Reshape.parse()` just before the `self.setParsed()` and after `self.parseOutput(0)`. The `perm` is set inside the 'fakeTranspose' and seems it does set inside `Reshape` parsing. I'm not sure whether it will encounter the problem you mentioned:
> But if we set that during Reshape parsing, the perm will change into something unexpected in layout propagation, which results in failure still.

Or it only happens when `transpose` is an _Attribute_ operator?


The codes for `fakeTranspose`is shown below (its logic is similiar to the `fakeBroadcast` in `binary` operator):
```
def fakeTranspose(self):
        # If the input (or output) tensor of Reshape
        # holds a special data layout semantic,
        # we need to insert Transpose before (or after) the Reshape operator
        # https://github.com/jackwish/tflite2onnx/issues/28

        assert(self.status.initialized)
        to_transpose = self.inputs[0]

        transposed_name = 'TFLITE2ONNX_Transposed_%s' % to_transpose.name
        transposed = self.TFactory.getWithRef(to_transpose, transposed_name, True)
        transposed.shape = [to_transpose.shape[p] for p in [0, 2, 3, 1]]
        transposed.setParsed()

        # Construct the additional transpose
        trans = Transpose(self.TFactory, -1)
        trans.attrs['perm'] = np.array([0, 2, 3, 1])

        trans.inputs.append(to_transpose)
        to_transpose.replaceConsumer(self, trans)
        self.replaceInput(to_transpose, transposed)

        trans.outputs.append(transposed)
        transposed.addProducer(trans)
        transposed.addConsumer(self)
        trans.setParsed()

        self.pre.append(trans)
```

**Comment by jackwish** [comment]
Oops! Transpose is indeed an _Terminate_ now. Sorry for my mistake, maybe I was checking with a legacy code base as I was on another machine. In this case we are all set.

For the code part, maybe we can check the details with a draft PR to see the whole picture.

Thanks!
