### ISSUE TITLE
Use case survey

### ISSUE THREAD

**Issue by jackwish** [jackwish/tflite2onnx#32]
It's significant to understand the use cases of our users. It will help us to decide how to shape `tflite2onnx` - what features we take as first priority. Please help to provide some information if possible. A possible template is as below, please feel free to propose new fields or ignore some.  :)

**How you generate/get the TFLite model?**

_Example: use TensorFlow quantization-aware training, or get it from mediapipe_

**Which ONNX backend you are going to use?**

_Example: TensorRT_

**What is the problem you try to solve?**

_Example: flower classification_

**Comment by deiruch** [comment]
### How you generate/get the TFLite model?
Download a pretrained, created by Google. I don't have the sources or training data for the model.

### Which ONNX backend you are going to use?
Microsoft.ML.OnnxRuntime.DirectML

### What is the problem you try to solve?
Background segmentation (what Google Meet, Microsoft Teams, Zoom, ... do)

**Comment by IkbeomJeon** [comment]
How you generate/get the TFLite model?
Mainly, download a pretrained, created by mediapipe.

Which ONNX backend you are going to use?
Microsoft.ML.OnnxRuntime (or Microsoft.ML.OnnxRuntime.DirectML)

What is the problem you try to solve?
3D Object tracking on hololens2

**Comment by jackwish** [comment]
@deiruch @IkbeomJeon thanks for your feedbacks :)

**Comment by tkys** [comment]
**How you generate/get the TFLite model?**
Models for the edge to create on Google AutoML

**Which ONNX backend you are going to use?**
Desktop machines with GPU or jetson nano with Tensor-RT

**What is the problem you try to solve?**
Object detection (  on streaming )

**Comment by kapulkin** [comment]
I train U-Net model with Tensorflow 2.0. My goal is to launch quantized model on any laptop. Thats, why I want to quantize model and later convert in into onnx.

Right now I use post-training int8 quantization with calibration. Quantization aware training is in plans.

**Comment by paulgavrikov** [comment]
**How you generate/get the TFLite model?**

Pretrained models from Google / MediaPipe

**Which ONNX backend you are going to use?**

torch.onnx

**What is the problem you try to solve?**

I am looking at various tasks and am looking for a converter that works with all sorts of tflite models.

**Comment by ram95014** [comment]
**How you generate/get the TFLite model?**

Pretrained models from Google / MediaPipe

**Which ONNX backend you are going to use?**

I convert ONNX to Intel's IR representation (OpenVINO)

**What is the problem you try to solve?**

I want to run the tflite models on openVINO capable edge devices

**Comment by jackwish** [comment]
Microsoft has re-invented the TensorFlow Lite to ONNX model converter in `tf2onnx`. They have more chances to enable more functionality.
