### ISSUE TITLE
Fold "FP16 weights -> Dequantize -> FP32 -> Conv/MatMul..." to "FP32 weights -> Conv/MatMul..."

### ISSUE THREAD

**Issue by jackwish** [jackwish/tflite2onnx#35]
ONNX quantization doesn't take FP16 as a quantized data type, therefore nearly all [FP16 quantized](https://www.tensorflow.org/lite/performance/post_training_quantization#float16_quantization) TFLite models are unsupported (see this [FAQ](https://github.com/jackwish/tflite2onnx/blob/master/docs/faq.md#fp16-quantization-model-doesnt-work)).

We recommend user switch to [full integer quantization](https://www.tensorflow.org/lite/performance/post_training_quantization#full_integer_quantization). But if the user cannot do that (for example no TensorFlow model available), we can fold "FP16 weights -> Dequantize -> FP32 -> Conv/MatMul..."  to "FP32 weights -> Conv/MatMul..." to workaround this issue.

**Comment by paulgavrikov** [comment]
It would be awesome if you could implement this! Unfortunately, the mediapipe models often rely on fp16 weights.

**Comment by ram95014** [comment]
I would second @paulgavrikov and request the fold from fp16 to fp32. Thanks

**Comment by jackwish** [comment]
@paulgavrikov @ram95014 Thanks for your feedback! I am very glad about that. This should be possible and should not take too much time but I was not working on it. It would be great if you can help!

In general, it could be divided into three steps:
1. Parse and build the graph just like ONNX can support FP16 as a quantization type. In this stage, we will have many patterns like `FP16 weights -> Dequantize -> FP32 Tensor -> Conv/MatMul` which will become illegal if convert to ONNX directly. I think we can support this stage currently but I have not tried that locally.
2. Walk the graph and fold FP16 weights. We can introduce a new pass like [layout propagation](https://github.com/jackwish/tflite2onnx/blob/master/tflite2onnx/graph.py#L101) or [handling quantization](https://github.com/jackwish/tflite2onnx/blob/master/tflite2onnx/graph.py#L105) - may be name like `foldFP16Weights`. Search the `FP16 weights -> Dequantize -> FP32 Tensor -> Conv/MatMul` in the graph (iterate the operators and check), for each pattern `P`:
    a) Cast _the weights_ of the `FP16 weights` to `FP32` directly, including changing `Tensor.data`, `Tensor.dtype` and etc.
    b) Detach the `FP16 weights` (which are actually _FP32 weights_ now) and the `Dequantize` operator, and the `FP32 Tensor` and the `Conv/MatMul` operator.
    c) Attach the casted `FP16 weights` (which are actually _FP32 weights_ now) to the `Conv/MatMul` operator.
    d) Remove the `Dequantize` and `FP32 Tensor` from the graph.
3. [Recollect the tensors and operator](https://github.com/jackwish/tflite2onnx/blob/master/tflite2onnx/graph.py#L110) like other graph operator passes.

It would be great if we can bring it up in the next minor release. I would suggest starting by adding a new operator to `tflite2onnx` to understand the code. They are pretty easy, you may find some in merged PRs.

**Comment by jackwish** [comment]
@paulgavrikov @ram95014 This functionality has been enabled, please try out with the latest code.
If anything looks wrong, please open issues and link to this one. Thanks!

**Comment by mikkelmedm** [comment]
Hi, should this be fixed? I am still having issues

**Comment by jackwish** [comment]
@mikkelmedm It has been fixed and protected by [this test](https://github.com/jackwish/tflite2onnx/blob/master/tests/test_ops.py#L33). What's the error you have?

**Comment by mikkelmedm** [comment]
Running it on a MediaPipe model I am getting an error like "FP16 is not tested, and might not work properly"
