### ISSUE TITLE
Command line tool: Help message should include version number

### ISSUE THREAD

**Issue by deiruch** [jackwish/tflite2onnx#43]
**Describe the bug**
When calling `tflite2onnx -h` it'd be useful to see the version number.

**Expected behavior**
```
tflite2onnx, Version 0.3.1 by jackwish, https://jackwish.net/tflite2onnx/
Convert TensorFlow Lite models to ONNX models

usage: tflite2onnx [-h] tflite_path onnx_path

positional arguments:
  tflite_path  Path to the input TFLite mode
  onnx_path    Path to save the converted ONNX mode

optional arguments:
  -h, --help   show this help message and exit
```

**Actual behavior**
```
usage: tflite2onnx [-h] tflite_path onnx_path

Convert TensorFlow Lite models to ONNX models

positional arguments:
  tflite_path  Path to the input TFLite mode
  onnx_path    Path to save the converted ONNX mode

optional arguments:
  -h, --help   show this help message and exit
```

**To Reproduce**
1. Invoke `tflite2onnx -h`

**Version**
v0.3.1

**Comment by jackwish** [comment]
Hi @deiruch thanks for raising this issue. Tip more information in the command line looks to be a great idea. Maybe some arg like `-v` or `--version` also. Are you interested in bringing such insight to the code base if you don't mind?

**Comment by deiruch** [comment]
I totally would if I knew Python. I don't even have a Python IDE installed... :(

**Comment by jackwish** [comment]
> I don't even have a Python IDE installed...
Aha neither do I :)
