### ISSUE TITLE
Mediapipe FP16 model converted to ONNX - results do not match.

### ISSUE THREAD

**Issue by ram95014** [jackwish/tflite2onnx#56]
I converted the publicly available tflite model from mediapipe [here](https://github.com/google/mediapipe/tree/master/mediapipe/modules/pose_landmark/pose_landmark_upper_body.tflite) using the latest checkout with the FP16 Quantizatoin Pattern Folding (version 0.3.1).
I then used the following code to compare the outputs of the two equivalent models using the [tflite interpreter](https://www.tensorflow.org/lite/guide/python) and onnxruntime. The outputs do not match. Still trying to track this down, but reporting the issue here. Attaching code below to compare the outputs from the two inferences.

`
import numpy as np
import tflite_runtime.interpreter as tflite

import onnxruntime

def onnx_infer(model_file, input_shape, input_data):
    sess = onnxruntime.InferenceSession(model_file)
    #print(sess.get_inputs()[0])
    #print(sess.get_outputs()[0])
    required_shape = sess.get_inputs()[0].shape
    #print('converting input_data with shape {} to shape {}'.format(input_shape, required_shape))
    input_data = input_data.reshape(required_shape)
    ort_inputs = {sess.get_inputs()[0].name: input_data}
    ort_outs = sess.run(None, ort_inputs)
    return ort_outs[0]

def tflite_infer(model_file):
    interpreter = tflite.Interpreter(model_path=model_file)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    input_shape = input_details[0]['shape']
    input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32) # range [0,1)

    interpreter.set_tensor(input_details[0]['index'], input_data)

    interpreter.invoke()

    output_data = interpreter.get_tensor(output_details[0]['index'])
    results = np.squeeze(output_data)

    return input_data, input_shape, results

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument(
          '-tfm',
          '--tflite_model_file',
          required=True,
          help='.tflite model to be executed')
    parser.add_argument(
          '-ofm',
          '--onnx_model_file',
          required=True,
          help='.onnx model to be executed')

    args = parser.parse_args()

    input_data, input_shape, results = tflite_infer(args.tflite_model_file)
    #print('input_shape :', input_shape)
    #print('input_data :', input_data)
    #print('tflite results :', results)

    results_onnx = onnx_infer(args.onnx_model_file, input_shape, input_data)
    #print('onnx results :', results_onnx)

    print('outputs ', 'match' if np.allclose(results, results_onnx) else 'don\'t match')
    #print(np.linalg.norm(results - results_onnx))
`

**Comment by jackwish** [comment]
@ram95014 is this still an issue for you?

I have not tested on any models but only a conv example: https://github.com/jackwish/tflite2onnx/blob/master/assets/tests/conv-quant-fp16.float32.tflite

**Comment by mlizhardy** [comment]
@ram95014 you closed this issue, did you solve it?
