### ISSUE TITLE
Basic conversion failing

### ISSUE THREAD

**Issue by subashp** [jackwish/tflite2onnx#58]
I wanted to convert a simple tflite into onnx model. I am hit with the issue [1] below. Below is the procedure to reproduce with a public model:
a) Download mobilenet from [2]
b) Setup a virtualenv (python3.6) with tensorflow(1.15.2 & 2.3 show same issue)
c) pip install tflite2onnx
d) tflite2onnx mobilenet_v1_1.0_224_quant.tflite .

[1] onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized data_type (tensor name: TFLITE2ONNX_Scalar_uint8_151): 2
[2] https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_1.0_224_quant_and_labels.zip

Can anyone pls help in letting me know if I am doing something wrong in using the tool?

**Comment by jackwish** [comment]
Hi @subashp thanks for reporting this issue, could you please report with [the bug report template](https://github.com/jackwish/tflite2onnx/issues/new?assignees=&labels=bug&template=bug-report.md&title=) and attach verbose log?

**Comment by subashp** [comment]
I moved on by not using this tool. So I don't have steps to provide to recreate. I will be closing this issue.
