### ISSUE TITLE
how to choose opset version？

### ISSUE THREAD

**Issue by jie311** [jackwish/tflite2onnx#61]
Some platform need opset version==10 to run the onnx model， but that of the converted onnx model is 11. How to change the opset version?

**Comment by jackwish** [comment]
@jie311 Thanks for raising this issue. I think I have written the explanation some place but cannot remember, so just update [the FAQ](https://github.com/jackwish/tflite2onnx/blob/master/docs/faq.md#custom-the-onnx-opset-version). And, quote as below.

> `tflite2onnx` is bound to ONNX Opset 11 currently. We don't plan to support a _custom_ opset version, since it requires opset semantic conversion which could be a burden to handle but I don't see the value of it. If you really need a custom opset, try [the ONNX Version Converter](https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md). And ask them to fix if there is any bug. (I have not used it :))

**Comment by jackwish** [comment]
I am going to close this issue as we won't fix it. Please feel free to reopen if you have any further questions. Thanks!
