### ISSUE TITLE
Operator request: Leaky Relu (Unsupported TFLite OP: 98 LEAKY_RELU!)

### ISSUE THREAD

**Issue by shilpan97** [jackwish/tflite2onnx#62]
**Note**: Currently, we only accept [TensorFlow Lite builtin operators](https://jackwish.net/tflite/docs/BuiltinOperator.m.html) request.

**What is the TensorFlow Lite operator you need**
(Please attach a tiny TFLite model `*.tflite`, which contains the operator you need ONLY.)
LeakyRelu

**What kind of service you are trying to deploy your model?**
.tflite to .onnx

**Would you like to contribute the operator?**

**Additional context**

**Comment by shilpan97** [comment]
using command for yolo tflite model: tflite2onnx.convert(tflite_path, onnx_path)

Error message:
             if opcode in tflite.BUILTIN_OPCODE2NAME:
                 name = tflite.opcode2name(opcode)
                 raise NotImplementedError("Unsupported TFLite OP: {} {}!".format(opcode, name))
             else:
               raise ValueError("Opcode {} is not a TFLite builtin operator!".format(opcode))

NotImplementedError: Unsupported TFLite OP: 98 LEAKY_RELU!

**Comment by shilpan97** [comment]
alpha typically 0.2

**Comment by jackwish** [comment]
@shilpan97 thanks for reporting this issue. Are you interested in contributing this operator? We have [documents](https://github.com/jackwish/tflite2onnx#documentation) to help with the implementation, check https://github.com/jackwish/tflite2onnx/blob/master/docs/how-to-enable-new-operator.md
