### ISSUE TITLE
Operator request: TFLite OP: 102 SPLIT_V

### ISSUE THREAD

**Issue by markostam** [jackwish/tflite2onnx#64]
**Note**: Currently, we only accept [TensorFlow Lite builtin operators](https://jackwish.net/tflite/docs/BuiltinOperator.m.html) request.

**What is the TensorFlow Lite operator you need**
(Please attach a tiny TFLite model `*.tflite`, which contains the operator you need ONLY.)

TFLite OP: 102 SPLIT_V

**What kind of service you are trying to deploy your model?**

Audio

**Would you like to contribute the operator?**

Maybe?

**Additional context**

**Comment by jackwish** [comment]
@markostam thanks for reporting this issue. Are you interested in contributing this operator? We have documents to help with the implementation, check https://github.com/jackwish/tflite2onnx/blob/master/docs/how-to-enable-new-operator.md
