### ISSUE TITLE
 Unsupported TFLite OP: 124 DENSIFY! (hand_landmark_sparse.tflite)

### ISSUE THREAD

**Issue by Travis-Lee** [jackwish/tflite2onnx#66]
The model form the site : <<https://github.com/google/mediapipe/tree/master/mediapipe/modules/hand_landmark/hand_landmark_saprse.tflite.>>,But when i   Convet tflite model to onnx, I have the problem is  Unsupported TFLite OP: 124 DENSIFY!  Tks for everyone's help.

**Comment by jackwish** [comment]
Hi @Travis-Lee thanks for reporting this issue. We are on the track of enabling more operators. Are you interested in implementing this operator? It's simple for most cases and we have rich documents to help: https://github.com/jackwish/tflite2onnx#documentation

**Comment by PINTO0309** [comment]
This is a home-made tool, but it is now compatible with **`Densify`**. It can also be converted to ONNX.
https://github.com/PINTO0309/tflite2tensorflow
