### ISSUE TITLE
ERROR Source ~/tflite2onnx does not appear to be a Python project: no pyproject.toml or setup.py

### ISSUE THREAD

**Issue by roachsinai** [jackwish/tflite2onnx#69]
**Describe the bug**

Get ERROR when run statement in build script: `ERROR Source ~/tflite2onnx does not appear to be a Python project: no pyproject.toml or setup.py`, this error raised by `python -m build --outdir ${root_dir}/assets/dist`.

**To Reproduce**

1. git clone https://github.com/jackwish/tflite2onnx.git && cd tflite2onnx
2. ./scripts/build-wheel.sh

**Version**

Which version are you using? latest tflite2onnx version.

**Additional context**

I'm in a virtual environment created by pyenv+virtualenv, python version is 3.7.4 on WSL.

**Comment by jackwish** [comment]
@roachsinai thanks for reporting this issue, I can reproduce it. It seems the behavior of `build` package has changed...

**Comment by jackwish** [comment]
@roachsinai Sorry for the delayed fix, have been very busy recently. Please check the latest version.
