### ISSUE TITLE
NotImplementedError: Unsupported TFLite OP: 32 CUSTOM!

### ISSUE THREAD

**Issue by JNingWei** [jackwish/tflite2onnx#75]
Hi author,
I encountered an unsupported when converting [face_landmark_with_attention.tflite](https://github.com/google/mediapipe/blob/master/mediapipe/modules/face_landmark/face_landmark_with_attention.tflite) to onnx:
```
Data type float16 not supported/tested yet, the generated model may contain error
NotImplementedError: Unsupported TFLite OP: 32 CUSTOM!
```
Any suggestions? Thanks.

**Comment by fabian57fabian** [comment]
Hello,
I also got this error by trying to convert an EfficientDetLite0 model.
It seems like not all ops can be converted...
Is it fixable?
